### ISSUE TITLE
downlaoder.py line 172 syntax error

### ISSUE THREAD

**Issue by jacobschellenberg** [OlavStornes/Scraping-Manual-Assistant#1]
I downloaded fresh, installed the requirements.txt, ran ./scrapingmanass.py and immediately get this error

Traceback (most recent call last):
  File "./scrapingmanass.py", line 6, in <module>
    import downloader as dl
  File "/home/sheep/git/Scraping-Manual-Assistant/downloader.py", line 172
    print(f'{index}/{total_queries} ', end='')

**Comment by jacobschellenberg** [comment]
I wasn't running the script with Python3.
